name: Deploy Laravel to DOM Cloud

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Laravel project to DOM Cloud
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DOMCLOUD_HOST }}
          username: ${{ secrets.DOMCLOUD_USER }}
          password: ${{ secrets.DOMCLOUD_PASS }}
          source: "."
          target: "/home/${{ secrets.DOMCLOUD_USER }}/public_html"
          strip_components: 0
          overwrite: true
          rm: false

      - name: Run Laravel setup commands via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOMCLOUD_HOST }}
          username: ${{ secrets.DOMCLOUD_USER }}
          password: ${{ secrets.DOMCLOUD_PASS }}
          script: |
            cd public_html
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force || true
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link
            echo " Deployment success to DOM Cloud!"
